### PR TITLE
Drop Ruby 2.2 and move to GitHub Actions

### PR DESCRIPTION
**Pull request by tagliala**
- Test against all supported Ruby versions
- Test ruby-head as experimental
- Use a gemfile specific for CI to avoid issues with committed Gemfile.lock

### CODE REVIEW

**Comment by tagliala** [comment]
Require GitHub actions to be enabled for this repo

Working run: https://github.com/tagliala/sablon/actions/runs/7740005756

**Comment by tagliala** [comment]
Rebased. There are failures against Ruby 3.4.0-dev because of OpenStruct

**Comment by senny** [comment]
Hi @tagliala 

Sorry for the huge delay on my part. Thanks for the effort to bring back CI. I'll get to this shortly 💛

**Comment by tagliala** [comment]
Done, two separate commits, if you prefer to make two different PRs

https://github.com/tagliala/sablon/actions/runs/9676026596

**Comment by senny** [comment]
@tagliala I think I would prefer to keep the simplicity from OpenStruct, can we declare `ostruct` as a development dependency instead of removing?

**Comment by tagliala** [comment]
> can we declare ostruct as a development dependency instead of removing?

I've tried, but Ruby 2.2 complains. I think I can do that the same. Will try and let you know

**Comment by tagliala** [comment]
Done. I don't know a better way to do this, IIRC `gemspec` does not allow conditional gem requirements

**Comment by senny** [comment]
You could try with `add_development_dependency`

**Comment by senny** [comment]
Or is the issue that you only want to declare it for certain Ruby versions? It should probably work with past Ruby Versions as well if we declare it. Or did you encounter problems doing so?

**Comment by tagliala** [comment]
> Or did you encounter problems doing so?

You can see the problem here: https://github.com/tagliala/sablon/actions/runs/9676486643/job/26696133567?pr=1

There is a safe navigation operator in `ostruct 0.1.0` which is being incorrectly bundled by 2.2

I don't know if this can be re-released as 0.1.1.

Otherwise if you want we can drop support for 2.2 in a separate PR

**Comment by senny** [comment]
Thanks for the details. I think it's safe to drop 2.2. That version has been EOL for a while.

**Comment by tagliala** [comment]
Done.

All green here: https://github.com/tagliala/sablon/actions/runs/9676560209/job/26696383672?pr=1

**Comment by senny** [comment]
awesome! Very glad to have CI back. Thank you so much for your work and patience 💛

**Pull request merged**
