### PR TITLE
Allow for registered content providers to determine the key used to extract values from context

### PR DESCRIPTION
**Pull request by Mongey**
sablon allows for custom content providers to be registered via 

```ruby
class FormsUrn < Sablon::Content::String
  def self.id
    :urn
  end
end

Sablon::Content.register(FormsUrn)
```

To use a mailMege tag for this Content type, you specify  `«=urn:example»`, but in the context, you're only supposed to pass in a non-type-qualified name e.g.

```ruby 
{
  "example" => "my value"
}
```

This PR allows you to change how the key transformation works for a registered `Sablon::Content` type, by specifying the `#key(regex)` method

e.g.

```ruby
  class FormsUrn < Sablon::Content::String
    def key(keyRegex)
      keyRegex.to_s # use the original key, do not only match to the second part of the regex 
    end

    def self.id
      :urn
    end
  end
```
would then allow you to pass through the fully-qualified name
```
{
  "urn:example" => "my value"
}
```

### CODE REVIEW

**Comment by senny** [comment]
Hi @Mongey, thank you for your contribution. I have only skimmed the patch quickly but it looks good. Please give me a few days to get to reviewing it properly.

**Comment by senny** [comment]
@Mongey could you provide some background on why the default naming within `context` does not work for you?

**Comment by Mongey** [comment]
Thanks for taking a look @senny
We have a bunch of documents that are already tagged using a mailmerge format of `«= urn:example:input »` , `«= urn:example:foobar »` etc.

Without this change we would need to pass in the following context.
```ruby
{
  "example:input" => "hello",
  "example:foobar" => "world"
}
```
However, we want to keep the mapping 1-1, for these types of tags, to avoid remapping the context keys to remove the `urn:` prefix

```ruby
{
  "urn:example:input" => "hello",
  "urn:example:foobar" => "world"
}
```

It's probably a bit of a strange use case 😅

**Comment by senny** [comment]
@Mongey thanks for the additional context. If I understand correctly, you are not really looking to add a custom content provider but mainly want to work around the fact that a `<type>:` prefix is something that Sablon treats differently in the context hash?

I understand your use-case and I do believe we can get this working (maybe by adding a runtime patch on your end). I'm not sure we want to extend the API to support this case though. It seems very specific to your current constraints.

**Comment by Mongey** [comment]
> @Mongey thanks for the additional context. If I understand correctly, you are not really looking to add a custom content provider but mainly want to work around the fact that a <type>: prefix is something that Sablon treats differently in the context hash?

Yeah exactly.

> I'm not sure we want to extend the API to support this case though. It seems very specific to your current constraints

no problem, I guess I can monkey patch or just use the fork

**Comment by senny** [comment]
@Mongey I'll take another look at the issue today. If anything, I think we can rearrange the internals a bit to make your patch a lot easier.

**Comment by senny** [comment]
@Mongey I pushed a proposed change in 46bfeeb9f220f14e560dabf30b3e8ccfa08398f0 that allows you to configure Sablon like so:

```ruby
Sablon::Context.content_regex = /\A((?!urn:)[^:]+):(.+)\z/
```

You also no longer need the custom `FormsUrn` type as keys not matching `content_regex` will just be treated as normal strings.

Let me know if that works for your use-case. If so, I can cut a new release.

**Comment by Mongey** [comment]
@senny That works perfectly, thank you

**Comment by senny** [comment]
@Mongey awesome. Thanks for the confirmation. I just released `0.4.1` that contains the patch.

**Pull request closed without merging**
